arm:
  trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - joint0
      - joint1
      - joint2
      - joint3

    constraints:
      goal_time: 5.0
      state_publish_rate: 25
